version: '3'

volumes:
  slapp_local_postgres_data: {}
  slapp_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: slapp_local_django
    container_name: slapp_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: slapp_production_postgres
    container_name: slapp_local_postgres
    volumes:
      - slapp_local_postgres_data:/var/lib/postgresql/data
      - slapp_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

#  docs:
#    image: slapp_local_docs
#    container_name: slapp_local_docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./slapp:/app/slapp:z
#    ports:
#      - '9000:9000'
#    command: /start-docs

  redis:
    image: redis:6
    container_name: slapp_local_redis
