# Generated by Django 4.2.10 on 2024-06-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipality",
            name="region",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
