# Generated by Django 4.2.10 on 2024-06-26 11:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0002_remove_municipality_region_delete_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("area", models.FloatField()),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.AddField(
            model_name="municipality",
            name="region",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="explorer.region"),
        ),
    ]
