# Generated by Django 4.2.10 on 2024-10-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0003_region_municipality_region"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PotentialareaWindSTP2027Repowering",
        ),
        migrations.DeleteModel(
            name="PotentialareaWindSTP2027SearchAreaForestArea",
        ),
        migrations.DeleteModel(
            name="PotentialareaWindSTP2027SearchAreaOpenArea",
        ),
        migrations.DeleteModel(
            name="PotentialareaWindSTP2027VR",
        ),
    ]
