# Generated by Django 4.2.10 on 2025-03-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0004_scenario_result_sensitivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alternative",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("divergence", models.FloatField()),
            ],
            options={
                "unique_together": {("divergence",)},
            },
        ),
        migrations.CreateModel(
            name="AlternativeResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region", models.CharField(max_length=255)),
                ("component", models.CharField(max_length=255)),
                ("carrier", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("min_capacity", models.FloatField()),
                ("max_capacity", models.FloatField()),
                ("min_cost", models.FloatField()),
                ("max_cost", models.FloatField()),
                (
                    "alternative",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="explorer.alternative"),
                ),
            ],
            options={
                "unique_together": {("alternative", "region", "component", "carrier", "type")},
            },
        ),
    ]
