# Generated by Django 4.2.10 on 2025-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0005_alternative_alternativeresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="objective",
            field=models.FloatField(default=0),
        ),
    ]
