# Generated by Django 4.2.10 on 2025-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0006_scenario_objective"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sensitivity",
            unique_together={
                ("scenario", "attribute", "component", "region", "perturbation_method", "perturbation_parameter")
            },
        ),
    ]
