# Generated by Django 4.2.10 on 2025-06-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0008_alter_airtraffic_id_alter_alternative_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="area",
        ),
        migrations.RemoveField(
            model_name="region",
            name="name",
        ),
    ]
