# Generated by Django 4.2.10 on 2025-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0009_remove_region_area_remove_region_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pvroof",
            name="area_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
