# Generated by Django 4.2.10 on 2025-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0012_potentialareapvroof_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PotentialareaWindSTP2018Vreg",
            new_name="PotentialareaWindSTP2018EG",
        ),
    ]
