# Generated by Django 4.2.10 on 2025-06-30 12:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0016_rpgolspvgroundoperating_rpgolspvgroundplanned_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rpgolswindoperating",
            options={"verbose_name": "Wind turbine", "verbose_name_plural": "Wind turbines"},
        ),
        migrations.AlterModelOptions(
            name="rpgolswindplanned",
            options={"verbose_name": "Wind turbine planned", "verbose_name_plural": "Wind turbines planned"},
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="capacity_gross",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="capacity_net",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="commissioning_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="commissioning_date_planned",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="decommissioning_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="geometry_approximated",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="hub_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="mastr_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="mun_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="explorer.municipality"
            ),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="operator",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="rotor_diameter",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="site_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="unit_count",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="voltage_level",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindoperating",
            name="zip_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="capacity_gross",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="capacity_net",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="commissioning_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="commissioning_date_planned",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="decommissioning_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="geometry_approximated",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="hub_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="mastr_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="mun_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="explorer.municipality"
            ),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="operator",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="rotor_diameter",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="site_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="unit_count",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="voltage_level",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rpgolswindplanned",
            name="zip_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rpgolswindoperating",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="rpgolswindplanned",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
