# Generated by Django 4.2.10 on 2025-06-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0017_alter_rpgolswindoperating_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rpgolswindoperating",
            name="geometry_approximated",
        ),
        migrations.RemoveField(
            model_name="rpgolswindplanned",
            name="geometry_approximated",
        ),
    ]
