# Generated by Django 4.2.10 on 2025-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0018_remove_rpgolswindoperating_geometry_approximated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
