# Generated by Django 4.2.10 on 2025-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0019_region_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alternative",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="alternative",
            name="region",
            field=models.CharField(default="OS", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="alternative",
            unique_together={("divergence", "region")},
        ),
    ]
